### ISSUE TITLE
/device42 v1.3.10 does not have a package available for mac

### ISSUE THREAD

**Issue by gowgopal83** [gerardlemetayerc/device42#70]
Any suggestions ?

```
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/gerardlemetayerc/device42 v1.3.10 does not have a package available for your current platform,
│ darwin_amd64.
│
```

**Comment by gerardlemetayerc** [comment]
Hello,

Noticed.

I will add it in the git workflow.

**Comment by gerardlemetayerc** [comment]
Hello,

It should be ok now (adressed in latest version - v1.3.12 - idk why but git didn't take correctly latest version of build.yaml on v1.3.11).

Do not hesitate if it's not good on your side.
